# Copyright 2024 FZI Research Center for Information Technology
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-FileCopyrightText: 2024 FZI Research Center for Information Technology
# SPDX-License-Identifier: Apache-2.0

volumes:
  energy-service-generics-devl-service-celery-broker:
  energy-service-generics-devl-service-celery-results:


services:
  energy-service-generics-devl-service-api:
    container_name: energy-service-generics-devl-service-api
    build:
      context: ./source
      target: esg-service-pandas
    init: true # Faster shutdown.
    entrypoint: [ "python" ]
    command: [ "-m", "esg.service.devl_service.api" ]
    restart: unless-stopped
    ports:
      - 8800:8800
    volumes:
      - ./source/esg:/usr/local/lib/python3.11/site-packages/esg
      - energy-service-generics-devl-service-celery-broker:/celery/broker/
      - energy-service-generics-devl-service-celery-results:/celery/results/
    environment:
      - CELERY__NAME=devl_service
      - 'CELERY__BROKER_URL=filesystem://'
      - 'CELERY__FS_TRANSPORT_BASE_FOLDER=/celery/'
      - VERSION=latest-devl

  energy-service-generics-devl-service-worker:
    container_name: energy-service-generics-devl-service-worker
    build:
      context: ./source
      target: esg-service-pandas
    init: true # Faster shutdown.
    entrypoint: [ "celery" ]
    command: [ "--app", "esg.service.devl_service.worker", "worker", "--loglevel=INFO" ]
    restart: unless-stopped
    volumes:
      - ./source/esg:/usr/local/lib/python3.11/site-packages/esg
      - energy-service-generics-devl-service-celery-broker:/celery/broker/
      - energy-service-generics-devl-service-celery-results:/celery/results/
    environment:
      - CELERY__NAME=devl_service
      - 'CELERY__BROKER_URL=filesystem://'
      - 'CELERY__FS_TRANSPORT_BASE_FOLDER=/celery/'
